kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq-pvc-1
  namespace: rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rabbitmq-storage
  